version: "3.7"

services:
    database:
        image: postgres
        container_name: database_crud
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=crud
        volumes:
            - pgdata:/data/postgres
    # app:
    #     build: .
    #     container_name: crud
    #     ports: 
    #         - 3333:3333
    #     volumes: 
    #         - .:/usr/app

volumes: 
    pgdata:
        driver: local